[package]
name = "repr"
version = "0.8.0"
edition = "2024"
description = "The regular-expression-as-linear-logic interpretation and its implementation"
license = "MIT/Apache-2.0"
keywords = ["regular-expression"]
categories = []
homepage = "https://github.com/rinarakaki/repr"
documentation = "https://docs.rs/repr"
rust-version = "1.85.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unconst = { version = "0.12", features = [] }
aho-corasick = { version = "1", optional = true }
# For skipping along search text quickly when a leading byte is known.
memchr = { version = "2", optional = true }
regex = "1"
regex-syntax = "0.8"

[features]
default = ["std", "perf-inline", "unicode", "regex-syntax/default"]
std = []
perf-inline = []
quotient = ["aho-corasick", "memchr"]


unicode = [
    "unicode-age",
    "unicode-bool",
    "unicode-case",
    "unicode-gencat",
    "unicode-perl",
    "unicode-script",
    "unicode-segment",
    "regex-syntax/unicode",
]
# Enables use of the `Age` property, e.g., `\p{Age:3.0}`.
unicode-age = ["regex-syntax/unicode-age"]
# Enables use of a smattering of boolean properties, e.g., `\p{Emoji}`.
unicode-bool = ["regex-syntax/unicode-bool"]
# Enables Unicode-aware case insensitive matching, e.g., `(?i)β`.
unicode-case = ["regex-syntax/unicode-case"]
# Enables Unicode general categories, e.g., `\p{Letter}` or `\pL`.
unicode-gencat = ["regex-syntax/unicode-gencat"]
# Enables Unicode-aware Perl classes corresponding to `\w`, `\s` and `\d`.
unicode-perl = ["regex-syntax/unicode-perl"]
# Enables Unicode scripts and script extensions, e.g., `\p{Greek}`.
unicode-script = ["regex-syntax/unicode-script"]
# Enables Unicode segmentation properties, e.g., `\p{gcb=Extend}`.
unicode-segment = ["regex-syntax/unicode-segment"]
